[package]
name = "pi_guid64"
version = "0.1.0"
authors = ["luob <luob@gmail.com>"]
edition = "2021"
description = "An GUID Generator"
repository = "https://github.com/GaiaWorld/pi_guid64.git"
license = "MIT OR Apache-2.0"
keywords = ["pi", "guid"]

[dependencies]
pi_time = "0.1"